# Generated by Django 6.0.4 on 2026-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_moved', 'Task moved'), ('comment_added', 'Comment added'), ('member_invited', 'Member invited'), ('task_assigned', 'Task assigned'), ('user_followed', 'User followed')], max_length=20),
        ),
    ]
