# Generated by Django 6.0.4 on 2026-05-14 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
        ('projects', '0002_projectinvite_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.projectinvite'),
        ),
    ]
